services:
  - type: web
    name: olsc-webhook
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 squarespace_webhook.py
    envVars:
      - key: PASSKIT_PROGRAM_ID
        sync: false
      - key: PASSKIT_API_BASE
        value: https://api.pub2.passkit.io
      - key: PASSKIT_API_KEY
        sync: false
      - key: PASSKIT_PROJECT_KEY
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: TIMEZONE
        value: America/New_York

  - type: web
    name: olsc-web-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: PROGRAM_ID
        sync: false
      - key: API_BASE
        value: https://api.pub2.passkit.io
      - key: PASSKIT_API_KEY
        sync: false
      - key: PASSKIT_PROJECT_KEY
        sync: false
      - key: TIMEZONE
        value: America/New_York
      - key: ADMIN_PASSWORD
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
